<?php
namespace App\Models;
class Permission extends \Spatie\Permission\Models\Permission {
	protected $fillable = ['name', 'guard_name'];

	public static function defaultPermissions() {
		return [
			'view_users',
			'add_users',
			'edit_users',
			'delete_users',
			'view_roles',
			'add_roles',
			'edit_roles',
			'delete_roles',
			'view_categories',
			'add_categories',
			'edit_categories',
			'delete_categories',
			'view_cities',
			'add_cities',
			'edit_cities',
			'delete_cities',
			'view_countries',
			'add_countries',
			'edit_countries',
			'delete_countries',
			'view_states',
			'add_states',
			'edit_states',
			'delete_states',
			'view_conversations',
			'add_conversations',
			'edit_conversations',
			'delete_conversations',
			'view_messages',
			'add_messages',
			'edit_messages',
			'delete_messages',
			'view_favorite',
			'add_favorite',
			'edit_favorite',
			'delete_favorite',
			'view_ad',
			'add_ad',
			'edit_ad',
			'delete_ad',
			'view_comment',
			'add_comment',
			'edit_comment',
			'delete_comment',
			'view_bank',
			'add_bank',
			'edit_bank',
			'delete_bank',
			'view_account',
			'add_account',
			'edit_account',
			'delete_account',
			'view_follower',
			'add_follower',
			'edit_follower',
			'delete_follower',
		];
	}
}
